# Generated by Django 3.0.8 on 2020-07-27 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apiserver', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postviews',
            name='blog_claps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postviews',
            name='blog_view_count',
            field=models.IntegerField(default=0),
        ),
    ]
